// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqKQDFRsWxxnGWpZD7Jhk0dWop_WeBVc',
    appId: '1:1072125858096:web:47d9ba52cbda19f7bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    authDomain: 'camply-c99bb.firebaseapp.com',
    storageBucket: 'camply-c99bb.firebasestorage.app',
    measurementId: 'G-Z294BZJRQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Vg0KHSo0sC3cc7efsrqGALpE7CYJP3g',
    appId: '1:1072125858096:android:a9cc071f48223670bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    storageBucket: 'camply-c99bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNFC27TPOel3HXUUbE2trwEJ89r3-8UE',
    appId: '1:1072125858096:ios:7c8eab6de3118848bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    storageBucket: 'camply-c99bb.firebasestorage.app',
    androidClientId: '1072125858096-0t48s67sskucngua65m25msen12na56f.apps.googleusercontent.com',
    iosClientId: '1072125858096-036mtr8daatnimqqs2ddp2h9och5smot.apps.googleusercontent.com',
    iosBundleId: 'com.example.userprofile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDNFC27TPOel3HXUUbE2trwEJ89r3-8UE',
    appId: '1:1072125858096:ios:7c8eab6de3118848bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    storageBucket: 'camply-c99bb.firebasestorage.app',
    androidClientId: '1072125858096-0t48s67sskucngua65m25msen12na56f.apps.googleusercontent.com',
    iosClientId: '1072125858096-036mtr8daatnimqqs2ddp2h9och5smot.apps.googleusercontent.com',
    iosBundleId: 'com.example.userprofile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXqKQDFRsWxxnGWpZD7Jhk0dWop_WeBVc',
    appId: '1:1072125858096:web:de2d6649aa207734bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    authDomain: 'camply-c99bb.firebaseapp.com',
    storageBucket: 'camply-c99bb.firebasestorage.app',
    measurementId: 'G-FTY015DLMS',
  );
}
