// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBududi0uLHYV7TEJgspb3mxb1F6GhJzM',
    appId: '1:610330807396:web:0acec910c764e74e08e371',
    messagingSenderId: '610330807396',
    projectId: 'fir-proj-2e019',
    authDomain: 'fir-proj-2e019.firebaseapp.com',
    databaseURL: 'https://fir-proj-2e019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-proj-2e019.firebasestorage.app',
    measurementId: 'G-XW0DFC4MCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7GYzTjlBAVmpKsG-ovDlDlNUCp1DAMgs',
    appId: '1:610330807396:android:663acfe7ac50a19e08e371',
    messagingSenderId: '610330807396',
    projectId: 'fir-proj-2e019',
    databaseURL: 'https://fir-proj-2e019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-proj-2e019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATufdvN4_sKjulR4lY-LO3Gaha3FRGwys',
    appId: '1:610330807396:ios:2c907305d468279b08e371',
    messagingSenderId: '610330807396',
    projectId: 'fir-proj-2e019',
    databaseURL: 'https://fir-proj-2e019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-proj-2e019.firebasestorage.app',
    iosBundleId: 'com.example.camply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATufdvN4_sKjulR4lY-LO3Gaha3FRGwys',
    appId: '1:610330807396:ios:2c907305d468279b08e371',
    messagingSenderId: '610330807396',
    projectId: 'fir-proj-2e019',
    databaseURL: 'https://fir-proj-2e019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-proj-2e019.firebasestorage.app',
    iosBundleId: 'com.example.camply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBududi0uLHYV7TEJgspb3mxb1F6GhJzM',
    appId: '1:610330807396:web:5b8189d19211a90808e371',
    messagingSenderId: '610330807396',
    projectId: 'fir-proj-2e019',
    authDomain: 'fir-proj-2e019.firebaseapp.com',
    databaseURL: 'https://fir-proj-2e019-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-proj-2e019.firebasestorage.app',
    measurementId: 'G-K0HSJW9B8M',
  );
}
