// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXqKQDFRsWxxnGWpZD7Jhk0dWop_WeBVc',
    appId: '1:1072125858096:web:829da06aa4350a05bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    authDomain: 'camply-c99bb.firebaseapp.com',
    storageBucket: 'camply-c99bb.firebasestorage.app',
    measurementId: 'G-YRVPXHRB89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Vg0KHSo0sC3cc7efsrqGALpE7CYJP3g',
    appId: '1:1072125858096:android:2d085887e1882706bc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    storageBucket: 'camply-c99bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDNFC27TPOel3HXUUbE2trwEJ89r3-8UE',
    appId: '1:1072125858096:ios:40686be3edfd3f9ebc38f5',
    messagingSenderId: '1072125858096',
    projectId: 'camply-c99bb',
    storageBucket: 'camply-c99bb.firebasestorage.app',
    iosBundleId: 'com.example.camply',
  );
}
